/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxScuRcu.h"

#include "led_driver.h"
#include "aswdummy.h"
#include "can_driver_TC375_LK.h"
#include "can_driver.h"
#include "reset_TC375_LK.h"

#include <stdio.h>

//extern version_info global_info;

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;


void process_can(uint32_t* rxData, IfxCan_DataLengthCode dlc){

    if(dlc <= 0)
    {
        // TODO do nothing?
        return;
    }

//    uint8_t* data_ptr = (uint8_t*)rxData;
//
//    FILE * f3 = fopen("terminal window 3", "rw");
//    fprintf(f3, "Hello, window 3.\n");
//    fprintf(f3, "dlc: %d\n", dlc);
//    for (int i = 0; i < dlc; i++)
//    {
//        fprintf(f3, "0x%02hhX ", data_ptr[i]);
//    }
//    uint32_t data = *rxData;
//    fprintf(f3, "0x%x\n", data);
//    fprintf(f3, "\n");
//    fclose(f3);

    uint32_t reset_msg = 0x00013e02; // Currently tester present

    if (reset_msg == *rxData){
        triggerSwReset(IfxScuRcu_ResetType_application);
    }
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    ledInitDriver();

    canInitDriver(process_can);

    while(1)
    {
        alternating_blinking();
    }
}
